import { describe, expect, it } from "vitest";
import { calculateChannelMetrics, calculatePilotMetrics } from "./metrics";

describe("reply assistant pilot metrics", () => {
  it("calculates Website resolution, escalation, provider, and public update metrics", () => {
    const metrics = calculateChannelMetrics({
      sessions: 8,
      meaningfulTurns: 10,
      responses: 9,
      directTemplateReplies: 6,
      noReply: 1,
      humanReviewsOpened: 3,
      humanReviewsResolved: 2,
      alertsQueued: 3,
      alertsDeduplicated: 2,
      alertsSent: 1,
      alertsFailed: 1,
      websiteHumanReplies: 2,
      rateBlocks: 4,
      budgetBlocks: 1,
      providerCalls: 7,
      inputTokens: 700,
      cachedInputTokens: 70,
      outputTokens: 140,
      totalCostMicrousd: 3_500,
      totalLatencyMs: 2_100,
      publicUpdates: 8,
      totalPublicUpdateLatencyMs: 4_000,
      crossSessionIsolation: "test_only_invariant",
      automaticBusinessActions: 0,
      automaticSends: 0,
    });

    expect(metrics).toMatchObject({
      directAutomatedResolutionRate: 0.7,
      humanEscalationRate: 0.3,
      averageProviderLatencyMs: 300,
      averagePublicUpdateLatencyMs: 500,
      automaticBusinessActions: 0,
      automaticSends: 0,
    });
  });

  it("uses explicit stable denominators", () => {
    expect(calculatePilotMetrics({
      totalIncomingEligible: 20,
      rawCustomerEvents: 24,
      staffContextEvents: 8,
      meaningfulTurns: 20,
      aggregatedFragments: 4,
      acknowledgementsSuppressed: 2,
      draftsGenerated: 10,
      acceptedUnchanged: 4,
      editedAccepted: 3,
      rejected: 2,
      gateBlocked: 5,
      outputValidatorBlocked: 1,
      providerCalls: 12,
      policyViolationAttempts: 1,
      totalCostMicrousd: 2_400,
      totalLatencyMs: 6_000,
      imageProviderCalls: 3,
      imageInputTokens: 90,
      imageCachedInputTokens: 15,
      imageOutputTokens: 30,
      imageTotalCostMicrousd: 600,
      imageTotalLatencyMs: 1_200,
      imageFailures: 1,
      imageCleanupDeleted: 2,
      imageCleanupFailures: 1,
      imageContexts: 5,
      imageAnalysesSucceeded: 3,
      imageAnalysesBlocked: 2,
      imageAwareDraftsGenerated: 2,
      imageAwareAcceptedUnchanged: 1,
      imageAwareEditedAccepted: 1,
      imageAwareRejected: 0,
      imageRequestOriginalRecommendations: 2,
      imageAwareTotalCostMicrousd: 900,
      totalActualHumanReplies: 12,
      matchedHumanReplies: 8,
      unmatchedHumanReplies: 4,
      acceptedUnchangedHumanReplies: 3,
      editedHumanReplies: 4,
      independentlyWrittenHumanReplies: 1,
      reusableCaseMemories: 5,
      excludedHighRiskCases: 2,
      casesRetrievedInDrafts: 7,
      learningCandidatesPending: 4,
      learningCandidatesApproved: 2,
      learningCandidatesRejected: 1,
      commonEditReasons: [{ code: "missing_next_step", count: 4 }],
    })).toMatchObject({
      directAcceptanceRate: 0.4,
      assistedAcceptanceRate: 0.7,
      rejectionRate: 0.2,
      gateBlockRate: 0.25,
      policyViolationRate: 1 / 12,
      averageCostPerDraftMicrousd: 240,
      averageLatencyMs: 500,
      averageImageCostPerCallMicrousd: 200,
      averageImageLatencyMs: 400,
      combinedCostMicrousd: 3_000,
      imageAnalysisSuccessRate: 0.6,
      imageRequestOriginalRate: 2 / 3,
      averageImageAwareCostPerDraftMicrousd: 450,
      imageAwareDirectAcceptanceRate: 0.5,
      imageAwareEditRate: 0.5,
      imageAwareRejectionRate: 0,
    });
  });

  it("returns zero for zero denominators", () => {
    expect(calculatePilotMetrics({
      totalIncomingEligible: 0, draftsGenerated: 0, acceptedUnchanged: 0, editedAccepted: 0,
      rawCustomerEvents: 0, staffContextEvents: 0, meaningfulTurns: 0,
      aggregatedFragments: 0, acknowledgementsSuppressed: 0,
      rejected: 0, gateBlocked: 0, outputValidatorBlocked: 0, providerCalls: 0,
      policyViolationAttempts: 0, totalCostMicrousd: 0, totalLatencyMs: 0,
      imageProviderCalls: 0, imageInputTokens: 0, imageCachedInputTokens: 0,
      imageOutputTokens: 0, imageTotalCostMicrousd: 0, imageTotalLatencyMs: 0,
      imageFailures: 0, imageCleanupDeleted: 0, imageCleanupFailures: 0,
      imageContexts: 0, imageAnalysesSucceeded: 0, imageAnalysesBlocked: 0,
      imageAwareDraftsGenerated: 0, imageAwareAcceptedUnchanged: 0,
      imageAwareEditedAccepted: 0, imageAwareRejected: 0,
      imageRequestOriginalRecommendations: 0, imageAwareTotalCostMicrousd: 0,
      totalActualHumanReplies: 0, matchedHumanReplies: 0, unmatchedHumanReplies: 0,
      acceptedUnchangedHumanReplies: 0, editedHumanReplies: 0,
      independentlyWrittenHumanReplies: 0, reusableCaseMemories: 0,
      excludedHighRiskCases: 0, casesRetrievedInDrafts: 0,
      learningCandidatesPending: 0, learningCandidatesApproved: 0,
      learningCandidatesRejected: 0,
      commonEditReasons: [],
    })).toMatchObject({
      directAcceptanceRate: 0,
      policyViolationRate: 0,
      averageLatencyMs: 0,
      averageImageCostPerCallMicrousd: 0,
      averageImageLatencyMs: 0,
      combinedCostMicrousd: 0,
      imageAnalysisSuccessRate: 0,
      imageRequestOriginalRate: 0,
      averageImageAwareCostPerDraftMicrousd: 0,
      imageAwareDirectAcceptanceRate: 0,
      imageAwareEditRate: 0,
      imageAwareRejectionRate: 0,
    });
  });
});
