import type { FormOrderRow } from "@/server/forms/forms-workbench-service";

export const formOrderRow: FormOrderRow = Object.freeze({
  id: "job-1",
  source: "manual",
  version: "2026-08-05T01:00:00.000Z",
  submittedAt: "2026-08-05T00:00:00.000Z",
  reference: "07188",
  webOrderNumber: "6304",
  size: "A0",
  urgent: true,
  neededDate: "2026-08-12",
  deliveryMethod: "post",
  customerSource: "rnr",
  customerName: "Elena Lasalo",
  customerEmail: "elena@example.test",
  customerPhone: "0210000000",
  assignedUserId: "artist-1",
  artistName: "Rosemary",
  status: "designing",
  paymentStatus: "paid",
  milestones: {
    fileSent: true,
    downloaded: true,
    customerNotified: false,
    printed: false,
    completed: false,
    delivered: false,
  },
  bankRecon: "Arrive",
  finance: {
    amountOwingCents: 13000,
    amountPaidCents: 10000,
    amountPayableCents: 23000,
    artistFeeCents: 5000,
  },
  remark: "A0 portrait canvas",
  submittedBy: "Rosemary",
});
